function Denoise(fileName)
    [x, fs] = audioread(fileName); % считывание записи
    xt = x'; % транспонирование сигнала
    ch1 = xt(1, :); % получение первого канала
    ch2 = xt(2, :); % получение второго канала
    newCh1 = wdenoise(ch1,14, ...
        'Wavelet', 'sym4', ...
        'DenoisingMethod', 'Minimax', ...
        'ThresholdRule', 'Soft', ...
        'NoiseEstimate', 'LevelDependent');

    newCh2 = wdenoise(ch2,14, ...
        'Wavelet', 'sym4', ...
        'DenoisingMethod', 'Minimax', ...
        'ThresholdRule', 'Soft', ...
        'NoiseEstimate', 'LevelDependent');
    newXt = [newCh1; newCh2];
    newX = newXt';
    audiowrite(strcat(fileName, '_Denoised.wav'), newX, fs);
end